name: Trivy Secret Scan

on:
  pull_request:
    branches: 
      - main
      - dev*

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v2
        with:
          version: 0.65.0

      - name: Run Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs           # file system scan
          scanners: secret        # run secret scanner
          format: table           # optional: table/json/sarif
          exit-code: 1            # fail on findings
          ignore-unfixed: true
